---
# Available Capes
capes:
   - Absorption_Cape.png
   - Angel_Cape.png
   - Batman_Cape.png
   - Bear_Cape.png
   - Blue_Cape.png
   - Brown_Bear_Cape.png
   - Buggy_Cape.png
   - Bug_Cape.png
   - Bunny_Cape.png
   - Bun_Cape.png
   - Champion_Cape.png
   - Chicken_Cape.png
   - Chicken_White_Cape.png
   - Christmass_2021_Cape.png
   - Christmass_2022_Cape.png
   - Christmass_2023_Cape.png
   - Coder_Cape.png
   - Cold_Cape.png
   - Cristal_Cape.png
   - Cursive_Cape.png
   - Death_Cape.png
   - Deer_Cape.png
   - Developer_Cape.png
   - Dimension_Cape.png
   - Dodge_Cape.png
   - Ducky_Cape.png
   - Egghunt_Cape.png
   - Endermen_Cape.png
   - Eyes_Cape.png
   - Fire_Cape.png
   - Flower_Heart_Cape.png
   - Fox_Cape.png
   - F_Cape.png
   - Gamer_Cape.png
   - Glizzy_Cape.png
   - Grrr_Cape.png
   - Hacker_Cape.png
   - Health_Cape.png
   - Heart_Cape.png
   - Hot_Cape.png
   - Iron_Elytra_Cape.png
   - Japanese_Cape.png
   - Japan_Cape.png
   - Lightning_Cape.png
   - LOO_Cape.png
   - Love_Cape.png
   - L_Black_Cape.png
   - L_Blue_Cape.png
   - Magic_Cape.png
   - Maroon_Cape.png
   - Minecon_Live_Cape.png
   - Mineshow_Cape.png
   - Minion_Cape.png
   - ML_Cape.png
   - Moi_Head_Cape.png
   - Money_Cape.png
   - Moon_and_Stars_Cape.png
   - Mozart_Cape.png
   - Nether_Cape.png
   - Nike_Cape.png
   - Ninja_Cape.png
   - Nintedo_Cape.png
   - Oof_Cape.png
   - Orange_Cape.png
   - Pacman_Cape.png
   - Pickaxe_Cape.png
   - Purple_Cape.png
   - Red_Flower_Cape.png
   - Rick_Roll_Cape.png
   - Rock_Happy_Cape.png
   - Rock_Sad_Cape.png
   - Sakura_Cape.png
   - Shield_Cape.png
   - Singapore_Cape.png
   - Skyline_Cape.png
   - SkyPlot_Cape.png
   - Snowman_Cape.png
   - Space_and_Time_Cape.png
   - Space_Cape.png
   - Stinky_Cape.png
   - Sunny_Cape.png
   - S_Cape.png
   - TapL_Wow_Cape.png
   - Tiktok_Cape.png
   - Trash_Cape.png
   - Turtle_Cape.png
   - Twitch_Cape.png
   - Uchiha_Cape.png
   - Venom_Cape.png
   - Wolf_Cape.png
   - World_Cape.png
   - Youtube_Cape.png
# Available Costumes
costumes: []
...